"""Initial migration.

Revision ID: 0ba7eeec7a40
Revises:
Create Date: 2025-09-07 20:22:07.960728

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ba7eeec7a40"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "click",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("clicked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["email.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "open",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["email.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("open")
    op.drop_table("click")
    op.drop_table("email")
    op.drop_table("campaign")
    # ### end Alembic commands ###
